# Site settings
title: Rodrigo Hormazabal
description: AI Research Scientist
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rodrigo
user_description: I'm a Research Scientist @ <a href="https://www.lgresearch.ai/">LG AI Research</a> and PhD Student at the Kim Jaechul <a href="https://gsai.kaist.ac.kr/">Graduate School of AI</a> of Korea Advanced Institute of Science and Technology (KAIST), under the supervision of Professor <a href="https://sites.google.com/site/jaegulchoo/">Jaegul Choo</a>.
user_title: Research Scientist @ LG AI Research
email: rodrigo@lgresearch.ai
twitter_username: rshormazabal
github_username:  rshormazabal
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
